### ISSUE TITLE
gif android

### ISSUE THREAD

**Issue by em-j** [Emixam23/XamarinByEmixam23#1]
Hey, I implemented your code and didn't work. Only see black app. Can you help me ?

**Comment by Emixam23** [comment]
Hey!

I haven't coded since a while for this repository, so maybe because of an Update it doesn't work anymore...

This is the version I am using for my last project:

Gif.cs

    using PROJECT.Sources.Interfaces;
    using System;
    using Xamarin.Forms;

    namespace PROJECT.Sources.Controls
    {
        public class Gif : WebView
        {
            public string GifSource
            {
                set
                {
                    var html = new HtmlWebViewSource();

                    string size = String.Format(" style='width:{0};height:{1};'", App.ScreenSize.Width, (App.ScreenSize.Height / 100) * 90);

                    html.Html = String.Format(@"<html><body style='background: #000000;'><img src='{0}'{1}/></body></html>",
                        DependencyService.Get<IBaseUrl>().Get() + value, size);

                    SetValue(SourceProperty, html);
                    this.Margin = -10;
                }
                get { return (string)GetValue(SourceProperty); }
            }
        }
    }

Page.xaml.cs

    <control:Gif
        AbsoluteLayout.LayoutBounds="0.5, 0, 1, 0.9"
        AbsoluteLayout.LayoutFlags="All"
        GifSource="Gifs/example.gif" />

---

Now, if you don't understand **BaseUrl**, there is some information/code that can help you

Shared - IBaseUrl.cs

    namespace PROJECT.Sources.Interfaces
    {
        public interface IBaseUrl { string Get(); }
    }

Android - BaseUrl_Android.cs

    using PROJECT.Droid.Sources.DependencyServices;
    using PROJECT.Sources.Interfaces;
    using Xamarin.Forms;

    [assembly: Dependency(typeof(BaseUrl_Android))]
    namespace PROJECT.Droid.Sources.DependencyServices
    {
        public class BaseUrl_Android : IBaseUrl
        {
            public string Get()
            {
                return "file:///android_asset/";
            }
        }
    }

**Note: For Android by example, your gif file should be in the Assets folder, the build action should be `AndroidAsset`**
